### ISSUE TITLE
/doc/UImockup/Storybaord/

### ISSUE THREAD

**Issue by yw2** [CMPUT301W14T04/Team04Project#6]
Storyboard is done, the title of this issue is where I put it, see if there is any thing to add or change. And also, can anyone help me to put the slides on wiki, thanks.

**Comment by telbohtimy** [comment]
I'm not sure how to put a pdf in the wiki, but for images since they are in the repository copy their url then go to the wiki page and click on image in the tool bar then paste the url where it asks for it and itll be uploaded to the wiki.  If they are not in the repository you can put them in an issue then post that issue then copy the issue url and it will work in the same way

**Comment by gramirezualberta** [comment]
I upload the slices to google and put images on wiki. it should be ok by now!

**Comment by nyushko** [comment]
Can someone show me how to upload the file from the repository to the wiki? I have tried all the things you said but its not working for me. It is the file in Team04Project/doc/Umlmockup/UseCase

**Comment by telbohtimy** [comment]
Give me a minute i'll put them up just double check i took the right file

**Comment by nyushko** [comment]
Okie dokie thank you so much :)

**Comment by telbohtimy** [comment]
Well the wiki is linking them to an issue page make sure they are correct I guess I'll try to make it so the pictures are on the wiki and not in issues

**Comment by nyushko** [comment]
Those are the ones I need, but I'm not quite sure where you say they are linking to the wiki page. I'm aiming to put it in the Storyboard, just under all the comments.

**Comment by yw2** [comment]
You can put it in the Storyboard.pptx. I uploaded this file also in this directory. Then Gramirez knows how to put them in wiki

**Comment by telbohtimy** [comment]
The storyboard wiki page correct? I have them currently in their own wiki page.  You could edit the wiki page I put them in and copy those links and put them in story board
