### ISSUE TITLE
Soryboard

### ISSUE THREAD

**Issue by nyushko** [CMPUT301W14T04/Team04Project#7]
Hey so the storyboard that was uploaded looks a lot like the comments that I had already done, it just describes what each screen does. It's not for a specific use case (or like we talked about, for all the use cases). Guillermo do you have the pictures with like a picture of someone clicking on each button? Also, can I change the name of storyboard to comments?

**Comment by nyushko** [comment]
Looking at everyone else's it looks like you only need one use case. So do you have the pictures for just one use case? For example, I dunno, reply to comments?

**Comment by gramirezualberta** [comment]
well i did some scenario that a user may do with our app.

for example:
1. let say that the user install our app, and look all the Top level comment on the main screen that would look like this [Main Screen](https://github.com/CMPUT301W14T04/Team04Project/blob/master/doc/UImockup/Storybaord/MainScreenUser.jpg)
2. so now the user decide to look at one top level comment so he or she will click on one top level comment in the main screen (i don't know how to represent clicking on the image), after user click on the top level comment would appear  [this screen](https://github.com/CMPUT301W14T04/Team04Project/blob/master/doc/UImockup/Storybaord/TopLevelCommentUser.jpg). In this one show a top level comment and its replies.
3. now the user want to reply that top level comment, so the user click on the arrow button and send the user to [this screen](https://github.com/CMPUT301W14T04/Team04Project/blob/master/doc/UImockup/CreateComment.jpg). Basically, I'm assuming that the characteristics of top level comment and reply comment are the same, so i use reuse the same createCommentView for replies and top level comments.
4. if user want to add a photo to his/her comment would click in the picture button and alert dialog would show, so he/she can select either take a picture using the camera or from gallery (phone memory) [this screen](https://github.com/CMPUT301W14T04/Team04Project/blob/master/doc/UImockup/Storybaord/CreateCommentPicture.jpg) and click on post. This is pretty much the use case for replying a top level comment

**Comment by nyushko** [comment]
so... the storyboard is already done? as well as the comments?

**Comment by yw2** [comment]
I think I did the storyboard in the way that covers most use cases, except those Internet ones.

**Comment by nyushko** [comment]
So the storyboard and explanations of each screen is done? Your storyboard explains everything that can be done, that seems like comments to me

**Comment by yw2** [comment]
I refer to the last term project the TA gave us, they look pretty much the same.

**Comment by nyushko** [comment]
So both are done

**Comment by gramirezualberta** [comment]
well looking at other team's storyboard, it seems that they have some sequence for one use case as Nadine says. Our storyboard look more like commenting how the user may use our app, maybe it is to general to be consider as a storyboard. In doc/UImockup/storyboard, I covert some of the requirement for the project as my example i just gave here.

**Comment by nyushko** [comment]
Since both of those things were supposed to be my contribution to the project, I guess is there anything else that needs to be done? Otherwise I have nothing to put on the individual task and peer review for myself.

**Comment by gramirezualberta** [comment]
We still need an Use Case example in the storyboard
