### ISSUE TITLE
Making New Top-Level Comments

### ISSUE THREAD

**Issue by nyushko** [CMPUT301W14T04/Team04Project#9]
Hey Tarek, how far along are you on the "making a new top-level comment"?  The things I have to work on kind of depend on that, so I was hoping you could send me your code for that, or upload it on git hub. I know your things for the week were 1 and 2, but it seems like the first thing that needs to get done is number 3 (making a new top-level comment). How soon do you think that'll be done?
Thanks! 
Nadine

**Comment by telbohtimy** [comment]
I've been focusing on the usernames this week but of you need the top level comments I'll start on it as soon as possible I'll try to put at least a rough code tonight

**Comment by nyushko** [comment]
Awesome. Even if you could just tell me how you're gonna arrange the JSON file, it would be really helpful for sorting

**Comment by telbohtimy** [comment]
I was planning to save the comments in an array of objects with their information and just save it by the order they're in that array.
